# Generated by Django 5.0.2 on 2026-02-16 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('subject', models.CharField(choices=[('info', "Demande d'information"), ('account', 'Ouverture de compte'), ('credit', 'Demande de crédit'), ('complaint', 'Réclamation'), ('partnership', 'Partenariat'), ('other', 'Autre')], max_length=20, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='new', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('assigned_to', models.CharField(blank=True, max_length=100, verbose_name='Assigné à')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('consent_data_processing', models.BooleanField(default=False, verbose_name='Consentement traitement des données')),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Désinscrit le')),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('need', models.CharField(choices=[('savings', "Ouvrir un compte d'épargne"), ('current', 'Ouvrir un compte courant'), ('credit_personal', 'Demande de crédit personnel'), ('credit_school', 'Demande de crédit scolaire'), ('credit_business', 'Demande de crédit activité/PME'), ('info', "Demande d'information")], max_length=30, verbose_name='Besoin')),
                ('additional_info', models.TextField(blank=True, verbose_name='Informations complémentaires')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('contacted', 'Contacté'), ('appointment', 'Rendez-vous planifié'), ('completed', 'Dossier ouvert'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date du rendez-vous')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('assigned_to', models.CharField(blank=True, max_length=100, verbose_name='Assigné à')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('consent_data_processing', models.BooleanField(default=False, verbose_name='Consentement traitement des données')),
                ('preferred_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.agency', verbose_name='Agence souhaitée')),
            ],
            options={
                'verbose_name': 'Demande client',
                'verbose_name_plural': 'Demandes clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
