# Generated by Django 5.0.2 on 2026-02-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'agence")),
                ('address', models.TextField(verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('monday_hours', models.CharField(default='8h30 - 17h00', max_length=50, verbose_name='Lundi')),
                ('tuesday_hours', models.CharField(default='8h30 - 17h00', max_length=50, verbose_name='Mardi')),
                ('wednesday_hours', models.CharField(default='8h30 - 17h00', max_length=50, verbose_name='Mercredi')),
                ('thursday_hours', models.CharField(default='8h30 - 17h00', max_length=50, verbose_name='Jeudi')),
                ('friday_hours', models.CharField(default='8h30 - 17h00', max_length=50, verbose_name='Vendredi')),
                ('saturday_hours', models.CharField(default='Fermé', max_length=50, verbose_name='Samedi')),
                ('sunday_hours', models.CharField(default='Fermé', max_length=50, verbose_name='Dimanche')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('is_main', models.BooleanField(default=False, verbose_name='Agence principale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['-is_main', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(verbose_name='Description')),
                ('features', models.TextField(help_text='Une caractéristique par ligne', verbose_name='Caractéristiques')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant maximum')),
                ('duration_range', models.CharField(blank=True, max_length=100, verbose_name='Durée')),
                ('interest_rate', models.CharField(blank=True, max_length=50, verbose_name="Taux d'intérêt")),
                ('requirements', models.TextField(blank=True, verbose_name="Conditions d'éligibilité")),
                ('icon_class', models.CharField(blank=True, max_length=100, verbose_name="Classe d'icône")),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Produit de financement',
                'verbose_name_plural': 'Produits de financement',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('category', models.CharField(choices=[('financial', 'Partenaire financier'), ('academic', 'Partenaire académique'), ('training', 'Formation & Employabilité'), ('economic', 'Partenaire économique')], max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(verbose_name='Description')),
                ('features', models.TextField(help_text='Une caractéristique par ligne', verbose_name='Caractéristiques')),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant minimum')),
                ('interest_rate', models.CharField(blank=True, max_length=50, verbose_name="Taux d'intérêt")),
                ('icon_class', models.CharField(blank=True, help_text='Ex: savings, school, business', max_length=100, verbose_name="Classe d'icône")),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Produit d'épargne",
                'verbose_name_plural': "Produits d'épargne",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('role', models.CharField(max_length=200, verbose_name='Fonction/Activité')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
